name: svg_zoom_and_pan
version: 0.0.1
author: Krzysztof Rzymkowski <rzymek@gmail.com>
description: SVG zoom and pan support
homepage: https://github.com/rzymek/dartSvgZoomAndPan
dependencies:
  browser: '>=0.6.14'
